config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  resources :articles do
    resources :comments
    resources :tags
  end
  get 'articles/tagged/:name' => 'articles#show_tagged', as: :articles_tagged

  post 'alltags' => 'tags#show' 
  get 'alltags' => 'tags#show' 

end

app/models/article.rb
class Article
  include Mongoid::Document
  field :title, :type => String
  field :text, :type => String
  field :count_tags, :type => Integer
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, dependent: :destroy, inverse_of: :article
  validates :title, presence: true, length: {minimum: 5 , maximum: 150 }
  validates :text, presence: true, length: {minimum: 30}
  validates :count_tags, :numericality => { :greater_than => 0, :less_than => 6  }
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :commenter, type: String
  field :body, type: String
  belongs_to :article
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name, type: String
  has_and_belongs_to_many :articles, dependent: :destroy
  validates :name, presence: true, length: {maximum: 25, minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
  def index
    #Article.all.delete
    #Tag.all.delete
    #Comment.all.delete
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end

  def show_tagged
    @list_articles = []
    @select_tag = Tag.where( name: params[:name] )[0]
    @select_tag.article_ids.each do |article_id|
      @list_articles.push( Article.where( _id: article_id )[0] )
 #  render plain: Tag.where( name: params[:name] )[0].article_ids
    end
  end
 
  def new
    @new_article = Article.new
  end
 
  def edit
    @new_article = Article.find(params[:id])
    @p=0
    @temp= []
    while @p<@new_article.count_tags.to_i
      @temp[@p]= @new_article.tags[@p].name
      @p=@p+1
     end
     @temp2=@temp.join(',')
  end
 
  def create
    @temp2 = ""
    @new_article = Article.new(article_params)
    @tag = Tag.new(tag_params)    
    @count_tag = params.require(:article).permit(:count_tags)
    @i = 0
    @k = 0
    @tag_name = tag_params[:name].split(/[,]+/)
    @new_tags = []
    while @i<@count_tag[:count_tags].to_i
      @exists_tag = Tag.where( name: @tag_name[@i] )
      if @exists_tag.count>0
        @exists_tag = @exists_tag[0]
      else
        @exists_tag = Tag.new(name: @tag_name[@i])
#        @exists_tag.push( article_ids: @new_article._id )
        if @exists_tag.save
          @new_tags[@k] = @exists_tag
          @k = @k + 1 
        end
       end
      @new_article.push( tag_ids: @exists_tag._id)
      @exists_tag.push( article_ids: @new_article._id )
      @exists_tag.update
      @i = @i + 1
    end
    if @new_article.save
        redirect_to @new_article
    else
      @i = 0
      while @i<@k
        @new_tags[@i].delete
        @i = @i + 1
      end   
      render 'new'
     end
  end
 
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit( :title, :text, :count_tags)
    end
  private
    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    if params[:tag].presence.nil?   
      @tags = Tag.all
    else
      if params[:tag][:name].blank?
        @tags = Tag.all
      else      
        @tags = Tag.where(:name => /#{tag_params[:name]}/)
      end
    end   
  end
  def create
    @article = Article.find(params[:article_id])
    @tag = @article.tags.create(tag_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @tag = @article.tags.find(params[:id])
    @tag.destroy
    redirect_to article_path(@article)
  end
  private
  def tag_params
    params.require(:tag).permit( :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @new_article do |f| %>
  <% if @new_article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@new_article.errors.count, "error") %> Косячим, да?
      </h2>
      <ul>
        <% @new_article.errors.full_messages.each do |msg| %>
          <li style="color:#ff0000"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <table>
  <tbody>
   <tr>
    <td><%= f.label 'Идея', :style => 'width: 45px' %>
    <%= f.text_field :title, :style => 'width: 600px' %></td>
   </tr>  
   <tr>
    <td><br>
    <%= f.label 'Инструкции' %><br>
    <%= f.text_area :text, :rows => '15', :cols => '90', :style => 'resize: none' %>
    </td>
   </tr>
   <tr>
    <td><br>
     <label id="list_tags"></label><br>
     <%= f.label 'Метки' %>
     <%= fields_for :tag do |f2| %>
     <%= f2.hidden_field :name, :id =>"post_tags", :value => @temp2 %>
     <%= f.hidden_field :count_tags, :id =>"post_count" %>
     <% end %>
     <input type="text" id="add_tag">
     <button type="button" class="btn btn-default" onclick="AddTag()">Добавить</button>
    </td>
   </tr>
 </tbody>
</table>
<br>
 <%= f.submit 'Утвердить', :class => "btn btn-success btn-lg" %>
<% end %>
<br>
<script>
var tag_class = "bt btn-info btn-sm";
var del_class = "glyphicon glyphicon-remove-sign";
var seps = [' ',',',';'];
var tags_id_inner = [];
var tags_list = document.getElementById("post_tags").value;
var tags_list_arr = getTags(tags_list);
if(tags_list.length>0) RenderTags(tags_list_arr,0);
function getTags(list){
var tags=[];
var reg = "";
for(var i=0;i<seps.length;i++) reg=reg+seps[i];
var arr_list = list.match(new RegExp("([^"+reg+"]*)","g"));
for(var i=0;i<arr_list.length;i++) 
  if (arr_list[i]!='') tags = tags.concat(arr_list[i]);
tags = SetupDistinct(tags);
return tags;
}
function SetupDistinct(tags){
for(var i=0;i<tags.length;i++)
  for(var j=i+1;j<tags.length;j++)
    if(tags[i]==tags[j]) tags.splice(j,1);
return tags;
}
function SetupNewTags(tags,new_tags){
var temp_tags = [];
var flag=0;
if(tags.length==0)
  for(var i=0;i<new_tags.length;i++)
    temp_tags=temp_tags.concat(new_tags[i]);
else
  for(var i=0;i<new_tags.length;i++){
    flag=1;
    for(var j=0;j<tags.length;j++)
      if(new_tags[i]==tags[j]) flag=0;
    if(flag == 1) temp_tags = temp_tags.concat(new_tags[i]);
  }
return temp_tags;
}
function DelElemById(id){
var elem = document.getElementById(id);
if(elem!=null) elem.parentNode.removeChild(elem);
}
function SendMsgWithId(msg,id){
DelElemById(id);
var inner = document.getElementById("list_tags").innerHTML;
document.getElementById("list_tags").innerHTML = "<label style=\"color:#ff0000\" id=\""+id+"\">" +"error: "+ msg + "</label>"+ inner;
}
function AddTag(){
var tag = document.getElementById("add_tag");
var tag_count = document.getElementById("post_count");
var post_tags = document.getElementById("post_tags");
var tags = getTags(tag.value+","+tags_list);
tag.value="";
var new_tags = SetupNewTags(tags_list_arr,tags);
var count_tags = new_tags.length;
if(count_tags>0)
{
RenderTags(new_tags,tags_list_arr.length);
post_tags.value = tags.join();
tags_list = post_tags.value;
tags_list_arr = getTags(tags_list);
tag_count.value = tags.length;
}
}
function RenderTags(tags,count){
var inner1 = "<span id=\"";
var inner2 = "\" class=\""+tag_class+"\">";
var inner3 = "<a class=\""+del_class+"\" title=\"Удалить метку\" onclick=\"RemoveTag('";
var inner4 = "');\"></a></span>";
var inner = document.getElementById("list_tags").innerHTML;
for(var i=count;i<tags.length+count;i++)
  inner = inner+" "+ inner1+tags[i-count]+inner2+tags[i-count]+" "+inner3+tags[i-count]+inner4;
document.getElementById("list_tags").innerHTML = inner;
}
function RemoveTag(name_elem){
DelElemById(name_elem);
var temp = [];
var post_tags = document.getElementById("post_tags");
var tag_count = document.getElementById("post_count");
post_tags.value = SetupNewTags(temp.concat(name_elem),tags_list_arr).join();
tag_count.value--;
tags_list=post_tags.value;
tags_list_arr=getTags(tags_list);
}
</script>

app/views/articles/edit.html.erb
<div class="container">
<h1>Новый план</h1>
<%= render 'form' %>
<%= link_to 'Одуматься/Назад', article_path, :class => 'btn btn-danger btn-sm' %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1>Блог Повелителя Мира</h1>
<%= link_to 'Новый план захвата мира', new_article_path, :class => "btn btn-primary btn-lg" %>
<%= link_to 'Метки', alltags_path, :class => "btn btn-primary btn-lg" %>
<%= link_to 'Планы', articles_path, :class => "btn btn-success btn-lg" %>
<br><br>
<table class="table">
<thead>
</thead>
 <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %><br>
      <%= article.text %></td>
    </tr>
  <% end %>
</tbody>
</table>

</div>

app/views/articles/new.html.erb
<div class="container">
<h1>Новый план</h1>
<%= render 'form' %>
<%= link_to 'Одуматься/Назад', articles_path, :class => 'btn btn-danger btn-sm' %>
</div>

app/views/articles/show.html.erb
<div class="container">
<h2><p><%= @article.title %></p></h2>
<br><br>
<table class="table">
 <thead>
 </thead>
 <tbody>
  <tr><td><%= @article.text %><br><br><br>
  <p><%= render @article.tags %></p>
  <%= link_to 'Улучшить', edit_article_path(@article), :class => "btn btn-warning btn-sm" %>
  <%= link_to 'Уничтожить', article_path(@article), :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Вы уверены?' } %></td></tr>
  <tr><td>Восхищения сторонников:<br><br>
  <%= render @article.comments %></td></tr>
  <tr><td>Добавить восхищение:<br>
  <%= render 'comments/form'  %></td></tr>
</tbody>
</table>
<%= link_to 'Назад', articles_path, :class => "btn btn-primary btn-md" %>
<br><br>
</div>

app/views/articles/show_tagged.html.erb
<div class="container">
<h1>Блог Повелителя Мира</h1>
<%= link_to 'Новый план захвата мира', new_article_path, :class => "btn btn-primary btn-lg" %>
<%= link_to 'Метки', alltags_path, :class => "btn btn-primary btn-lg" %>
<%= link_to 'Планы', articles_path, :class => "btn btn-success btn-lg" %>
<br><br>
<table class="table">
<thead>
</thead>
 <tbody>
  <% @list_articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %><br>
      <%= article.text %></td>
    </tr>
  <% end %>
</tbody>
</table>

</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Слуга Твой:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Пожелания:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Убрать это', [comment.article, comment], :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Вы уверены?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label 'Имя Твое' %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :'Излагай' %><br>
    <%= f.text_area :body, :style => 'resize: none' %>
  </p>
  <p>
    <%= f.submit  %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" media="all">
  <script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_for([@article, @article.tags.build]) do |f| %>
  <p>
    <%= f.text_field :text %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tags/_tag.html.erb
<label class="bt btn-info btn-sm"><%= tag.name%></label>

app/views/tags/show.html.erb
<div class="container">
<h1>Блог Повелителя Мира</h1>
<%= link_to 'Новый план захвата мира', new_article_path, :class => "btn btn-primary btn-lg" %>
<%= link_to 'Метки', alltags_path, :class => "btn btn-success btn-lg" %>
<%= link_to 'Планы', articles_path, :class => "btn btn-primary btn-lg" %>
<br><br>
<%= form_for :tag, url: alltags_path do |f| %>
  <%= f.label 'Поиск по тегам' %>
  <%= f.text_field :name  %>
  <%= f.submit 'Искать' %>
<% end %>
<br>
<table class="table">
<thead>
<tbody>
<% 
@CountCols=4
@CountTags=@tags.count
@CountRows=@CountTags/@CountCols
@EtcTags=@CountTags-@CountCols*@CountRows
@i = 0
while @i<@CountRows
@j=0 
%>
<tr>
<% while @j<@CountCols %>
<td><%= link_to @tags[@i*@CountCols+@j].name, articles_tagged_path(:name => "#{@tags[@i*@CountCols+@j].name}"), :class => "btn btn-info btn-sm" %></td>
<%
@j=@j+1
end
%></tr>
<%
@i=@i+1
end
%><tr>
<%
@j=0
while @j<@EtcTags
%>
<td><%= link_to @tags[@i*@CountCols+@j].name, articles_tagged_path(:name => "#{@tags[@i*@CountCols+@j].name}"), :class => "btn btn-info btn-sm" %></td>
<%
@j=@j+1
end
%>
<%
@j=0
while @j<@CountCols-@EtcTags
%>
<td></td>
<%
@j=@j+1
end
%>
</tr>
 </tbody>
</table>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Hell!</h1>